### ISSUE TITLE
TypeError because of int instead of string in FixtureData

### ISSUE THREAD

**Issue by kschroeer** [DavidBadura/Fixtures#17]
The constructor of the FixtureData class now explicitly expects the key as string. That conflicts with my yaml file because data is an array in my case and so the key will be an int (0, 1, 2, ...):

```
editor_config:
    data:
          - name: "default_element_width"
            value: "60"
            type: "int"
            label: "config_default_element_width"
          - name: "upload_image_min_width"
            value: "200"
            type: "int"
            label: "config_upload_image_min_width"
```
